version: "3.9"

networks:
  custom_network:
    driver: bridge

services:
  database:
    image: postgres:13.9-alpine
    networks:
      - custom_network
    container_name: psql_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6.0
    networks:
      - custom_network
    container_name: pg-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
      
  backend:
    build: .
    networks:
      - custom_network
    ports:
      - 8080:8080
    depends_on:
      - database
      - pg-admin

volumes:
  postgres:
